org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

ae2_version=19.2.17
ae2wtlib_version=19.5.1
jei_version=19.44.0.403
neo_version_range=[21.1.215,)
java_version=21


## Mod Properties
mod_id=wcot_omnibridge
mod_name=WCWT Omniversal Bridge
mod_license=MIT
mod_version=1.0.0
mod_authors=muyu
mod_group_id=com.muyu.wcot
mod_description=Bridges UselessMod's Omniversal Patterns into AE2 WCWT's pattern encoding terminal.